version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s32lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-eq8ej2shdznk"
s3_prefix = "s32lambda"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
